#这些是支持的融资模式平台

吉斯丘: #替换为最多4个启用GitHub赞助商的用户名，例如，[user1，user2]
帕特隆: #用Patreon用户名替换
open_collective: #用单个开放的集体用户名替换
ko_fi: #替换为一个Ko-fi用户名
潮汐: #替换为单个Tidelift平台-名称/包-名称，例如，npm/babel
community_bridge: #替换为单个社区桥项目-名称，例如，cloud-foundry
liberapay: #替换为单个Liberapay用户名
issuehunt: #用一个IssueHunt用户名替换
lfx_crowdfunding: #替换为单个LFX众筹项目-名称，例如，云-铸造
极地的: #用单个Polar用户名替换
buy_me_a_coffee: #替换为Buy Me a Coffee用户名
习惯: #替换为最多4个自定义赞助网址，例如，['link1'，'link2']
